In [4]:
from os import chdir as cd
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

pathin = '/Users/ethan/Documents/GitHub/CLA_2019/Coding/Friday Exercises/Data/'
file = 'HearingMeHearingYou_Data.csv'

cd(pathin)

df = pd.read_csv(file)

In [2]:
df.head()

,ChildID,Visit,ASD,Gender,Age,ADOS,MSEL_EL,MSEL_VR,ChildMLU,ChildTokens,ChildTypes,ParentMLU,ParentTokens,ParentTypes,SharedType
0,1,1,0,Male,19.80,0,14,28,1.337349,194,19,3.671821,2417,478,5
1,1,2,0,Male,23.93,0,14,28,1.009009,223,18,3.913793,2762,516,2
2,1,3,0,Male,27.70,0,14,28,1.570370,481,98,4.405063,3215,472,80
3,1,4,0,Male,32.90,0,14,28,2.047619,438,150,4.475936,2814,654,75
4,1,5,0,Male,35.90,0,14,28,3.000000,640,208,5.284615,3075,708,130

In [5]:
sns.relplot(x="Visit", y="ChildTypes", hue="ASD", style="ASD",
            data=df);

AttributeError: module 'seaborn' has no attribute 'relplot'